#!/bin/sh
# Kikaha Simple Command Line
# Since: 07/Jan/2016

# VARIABLES
CWD=`pwd`
KDIR=$(cd `dirname "${0}"` && pwd)
VERSION="0.1.0-SNAPSHOT"

cd $CWD

# INCLUDES
for include in $KDIR/base/inc.*.sh; do
	. $include
done

kikaha_print_logo

# CONFIGURATIONS
for conf in $KDIR/conf/*.conf; do
	debug "Reading configuration: $(grape $conf)"
	. $conf
done

# ==================================================
#  Main
# ==================================================
plugin_name=$1

plugin_location=`kikaha_which_plugin $plugin_name`
if [ ! "$plugin_location" = "" ]; then
	shift
else
	plugin_name="build"
	plugin_location=`kikaha_which_plugin $plugin_name`
fi

. $plugin_location
debug "Plugin loaded: $(grape $plugin_name)"
kikaha_run_plugin $plugin_name $@

