#!/bin/sh
# Kikaha Simple Command Line
# Since: 07/Jan/2016

# VARIABLES
CWD=`pwd`
KDIR=$(cd `dirname "${0}"` && pwd)
VERSION="0.1.0-SNAPSHOT"

cd $CWD

# INCLUDES
for include in $KDIR/base/inc.*.sh; do
	. $include
done

kikaha_print_logo

# CONFIGURATIONS
for conf in $KDIR/conf/*.conf; do
	debug "Reading configuration: $(grape $conf)"
	. $conf
done

# LOAD VARIABLES FROM COMMAND LINE
for arg in $@; do
  name=`arg_name $arg`
  if [ ! "$name" = "${arg}" ]; then
    value=`arg_value $arg`
    export $name=$value
    debug "Command line variable $name: $value"
  fi
done

# ==================================================
#  Main
# ==================================================
plugin_name=$1

plugin_location=`kikaha_which_plugin $plugin_name`
if [ ! "$plugin_location" = "" -a ! "$plugin_name" = "build" ]; then
	shift
else
	plugin_name="build"
	plugin_location=`kikaha_which_plugin $plugin_name`
fi

. $plugin_location
debug "Plugin loaded: $(grape $plugin_name)"
debug "Plugin args: $@"
kikaha_run_plugin $plugin_name $@

